### PR TITLE
Added arm64 jobs in Travis-CI

### PR DESCRIPTION
**Pull request by ossdev07**
Travis-CI has added support for ARM64. Added ARM64 jobs in Travis-CI.

### CODE REVIEW

**Comment by jonathanunderwood** [comment]
Thanks for working on this. Some things that are needed:

- The travis job names don't currently distinguish arch, so it's tricky to see which is which. I think the job names should now include the arch.
- Please follow this article for git commit messages: https://chris.beams.io/posts/git-commit/ . In particular, please use the imperative style: "Add arm64 jobs to Travis", for example.

I notice that these builds are taking a really long time to run, so I am slightly hesitant about enabling this.

**Comment by jonathanunderwood** [comment]
It looks like the maximum time limit for a job on travis is 50 minutes, and the test suite on arm takes longer than that, so the arm jobs all fail.

The test suite has been getting larger and larger, I do think this needs revisiting.

**Comment by ossdev07** [comment]
> * The travis job names don't currently distinguish arch, so it's tricky to see which is which. I think the job names should now include the arch.

@jonathanunderwood should I put travis-job-name to ```linux-py35-amd64``` and ```linux-py35-arm64```.

> * Please follow this article for git commit messages: https://chris.beams.io/posts/git-commit/ . In particular, please use the imperative style: "Add arm64 jobs to Travis", for example.

Sure, I will update the commit message as per your suggestion.

> The test suite has been getting larger and larger, I do think this needs revisiting.

Yes, the arm64 jobs takes more time than amd64 if you agree we can enable arm64 jobs for python version 3.7 and 3.8 only for now.

Please share your suggestions, I will update the PR accordingly.

**Comment by ossdev07** [comment]
@jonathanunderwood could you please have a look at this PR.

**Comment by jonathanunderwood** [comment]
This isn't viable with the streams test suite taking so long, and that's a problem we need to solve. 
@tSed would you be able to rationalize down the test suite for the streams so that it completes on the same sort of timescale as the frames test suite?

**Comment by ossdev07** [comment]
@jonathanunderwood Just to inform the build wasn't taking this much longer time to execute earlier when I tested it in my Travis environment.

Also if you agree we can possibly enable the aarch64 builds for Python v3.7 or Python v3.8. Please do revert if something is required to be done from my end.

**Comment by tSed** [comment]
@jonathanunderwood @ossdev07 Hi, I've finally got some time to look into this issue.

I can do a PR reducing the number of tests and hopefully make them completing in the 50-minute window.

However, I think there is also something else with the underneath travis CI arm64 host platform, since the decompression the python-3.5 archive, on [arm64](https://travis-ci.org/github/python-lz4/python-lz4/jobs/632210567#L19), lasts about 4 times the duration on [amd64](https://travis-ci.org/github/python-lz4/python-lz4/jobs/632210566#L163).

**Comment by tSed** [comment]
@jonathanunderwood @ossdev07 see PR #195

**Comment by ossdev07** [comment]
Thanks, @tSed @jonathanunderwood Please suggest what needs to be done from my end in this PR so that you can consider it for the merge.

Also, I have checked the arm64 related builds after the changes you did and please have a look at the Travis-ci logs:
https://travis-ci.com/github/odidev/python-lz4

The tests are running only for python v3.5 ( build is not successful though ), and for rest of the python versions getting the below issue :

```
WARNING: Building wheel for coverage failed: [Errno 13] Permission denied: '/home/travis/.cache/pip/wheels/c5'
202
  WARNING: Building wheel for cryptography failed: [Errno 13] Permission denied: '/home/travis/.cache/pip/wheels/8d'
203
  WARNING: Building wheel for cffi failed: [Errno 13] Permission denied: '/home/travis/.cache/pip/wheels/6c'
204
Failed to build coverage cryptography cffi
205
ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
```
The permission issue is coming on some other python repositories as well this seems like a Travis issue and I am already in discussion with the Travis community regarding resolving the same. Please have a look:
 https://travis-ci.community/t/permission-issue-while-building-wheels-for-various-python-packages/7822/3

**Comment by jonathanunderwood** [comment]
Can you rebase this branch onto master, and we'll see if the builds complete now the streams tests are shorter.

**Comment by jonathanunderwood** [comment]
Looks like this is still failing in tests.

**Comment by ossdev07** [comment]
@jonathanunderwood As I mentioned in the above comment https://github.com/python-lz4/python-lz4/pull/188#issuecomment-607275017, the tests are failing due to permission issue on Travis-ci and for that, I have already raised an issue in Travis community.

But if you have any other suggestions to resolve the issues Please suggest and I will incorporate those changes in the PR.

**Comment by ossdev07** [comment]
@jonathanunderwood The tests are passing now for all the python versions and the permission issue has been resolved, only the following two commands are failing it will be really helpful if you could suggest why it must be failing:

1. git stash --all
2. cibuildwheel --output-dir dist

**Comment by jonathanunderwood** [comment]
> @jonathanunderwood The tests are passing now for all the python versions and the permission issue has been resolved, only the following two commands are failing it will be really helpful if you could suggest why it must be failing:
> 
>     1. git stash --all
> 
>     2. cibuildwheel --output-dir dist

I haven't had chance to look in detail, but cibuildwheel uses a docker container to produce manylinux wheels. I suspect that docker support may not be functional on the arm builders?

**Comment by ossdev07** [comment]
@jonathanunderwood Thanks for the quick response. I have a few things to ask, Please revert your feedback:

1. Can we skip the ```cibuildwheel --output-dir dist``` for the arm64 platform.
2. Can we add arm64 support for only the latest python versions ie, 3.7 and 3.8?
3. Also, please suggest why the ```git stash --all``` command is giving the following issue:

```
fatal: empty ident name (for <travis@travis-job-ossdev07-python-lz4-318723584.(none)>) not allowed
863
Cannot save the current index state" 
```

**Comment by jonathanunderwood** [comment]
> @jonathanunderwood Thanks for the quick response. I have a few things to ask, Please revert your feedback:
> 
>     1. Can we skip the `cibuildwheel --output-dir dist` for the arm64 platform.
> 

Without that, you won't get the compiled wheels, defeating the purpose of your proposed change.

>     2. Can we add arm64 support for only the latest python versions ie, 3.7 and 3.8?
> 

That's fine.

>     3. Also, please suggest why the `git stash --all` command is giving the following issue:
> 
> 
> ```
> fatal: empty ident name (for <travis@travis-job-ossdev07-python-lz4-318723584.(none)>) not allowed
> 863
> Cannot save the current index state" 
> ```

I am afraid I don't know. I suspect that's another Travis issue.

**Comment by ossdev07** [comment]
@jonathanunderwood I have successfully resolved the cibuild issue and also updated the travis.yml to add support for arm64 in the latest Python versions i.e v3.7 and v3.8.

Also, the git stash issue seems like something related to Travis hence I have raised an issue in Travis-ci community regarding the same, please have a look:
https://travis-ci.community/t/git-stash-issue-in-arm64/8363

**Comment by ossdev07** [comment]
@jonathanunderwood I have resolved the git stash issue as well in my Travis-ci environment, Please have a look at the logs:

https://travis-ci.com/github/odidev/python-lz4/jobs/324971888

I have included the below two commands to resolve the issue before git stash command:

```
git config --global user.email "odidev@puresoftware.com" 
git config --global user.name "odidev"
```
I think we will have to mention your details in the travis.yml to resolve the issue for this repository, Please share your thoughts on this.

**Comment by ossdev07** [comment]
Ping @jonathanunderwood could you please have a look at this PR.

**Comment by ossdev07** [comment]
Please could you share your thoughts on this @jonathanunderwood

**Comment by jonathanunderwood** [comment]
> @jonathanunderwood I have resolved the git stash issue as well in my Travis-ci environment, Please have a look at the logs:
> 
> https://travis-ci.com/github/odidev/python-lz4/jobs/324971888
> 
> I have included the below two commands to resolve the issue before git stash command:
> 
> ```
> git config --global user.email "odidev@puresoftware.com" 
> git config --global user.name "odidev"
> ```
> 
> I think we will have to mention your details in the travis.yml to resolve the issue for this repository, Please share your thoughts on this.

This looks like an ugly workaround for a problem that should be fixed by the Travis folks. However, since it's just a workaround, I suggest to simply set those values to some junk strings e.g.

"junk@junk.com" "junk".

**Comment by ossdev07** [comment]
@jonathanunderwood I checked the package with the changes you suggested in my local Travis first and then pushed the code again here too, but somehow the arm64 builds get timeout whenever I run it here and not when I run it my Travis environment. https://travis-ci.com/github/odidev/python-lz4

Also, this time amd64 builds are failing as well because of this command ```flake8 lz4 setup.py tests```, your thoughts?

**Comment by ossdev07** [comment]
Ping @jonathanunderwood could you please share your thoughts on this.

**Comment by jonathanunderwood** [comment]
> @jonathanunderwood I checked the package with the changes you suggested in my local Travis first and then pushed the code again here too, but somehow the arm64 builds get timeout whenever I run it here and not when I run it my Travis environment. https://travis-ci.com/github/odidev/python-lz4
> 

It's difficult to know when I don't have access  to your Travis environment. My guess would be a different time out threshold.

> Also, this time amd64 builds are failing as well because of this command `flake8 lz4 setup.py tests`, your thoughts?

Not sure, would need to look into it.

**Comment by jonathanunderwood** [comment]
Have just pushed a commit to master which fixes your flake8 issue.

**Comment by ossdev07** [comment]
@jonathanunderwood rebased and added ```travis_terminate $?``` to get more details on the stalled Travis builds. Please share your thoughts on this.

**Comment by ossdev07** [comment]
@jonathanunderwood It looks like the Travis builds didn't trigger in the last commit, could you please have a look and suggest the reason.

**Comment by ossdev07** [comment]
@jonathanunderwood  Please have a look at the PR, all the checks are passing now and cibuildwheel command is also working sucesfully for arm64.

**Comment by jonathanunderwood** [comment]
Thanks for your work on this.

**Pull request merged**
