### PR TITLE
Update CI to newest actions and Python 3.13

### LINKED ISSUE #287: Wheels for Python 3.13
Currently wheels for Python 3.13 are missing. This is one of 21 projects in the top 360 Python packages on PyPI to provide 3.12 wheels but not 3.13 wheels. Wheels are safe to build once Python starts releasing RCs.

### PR DESCRIPTION
**Pull request by jmg-duarte**
~Didn't do some of the actions since they had a specific version specifier and there's probably a reason for that~ Fixed

fixes #287 and unblocks #284 and #289 

closes #291 
closes #288

### CODE REVIEW

**Comment by jonathanunderwood** [comment]
There wasn't any major reason for pinning, so it's possible to update them all. Right now though it looks like builds are failing for this PR.

**Comment by jmg-duarte** [comment]
Will take a look here as well. I think this is blocking my other PR

**Comment by jmg-duarte** [comment]
I've addressed the CI issue and took the chance to handle:

- Fixing the Actions (of course!)
- Deprecating 3.8 as it is EOL
- Adding 3.13 

I've also updated the PR title

**Comment by hauntsaninja** [comment]
Hello! Thanks for maintaining lz4. I'm a little confused by https://github.com/python-lz4/python-lz4/releases/tag/v4.4.0 — I don't see a corresponding release on PyPI https://pypi.org/project/lz4/#history

**Comment by jmg-duarte** [comment]
@hauntsaninja what happened was:
* this build failed
* reported on https://github.com/python-lz4/python-lz4/issues/293
* fixed on https://github.com/python-lz4/python-lz4/pull/285
* never rebuilt

**Comment by codesorcery** [comment]
@jonathanunderwood @jmg-duarte will there be a new build supporting Python 3.13?
The latest version of https://pypi.org/project/trino/ now depends on this package, which blocks us from updating since there are currently no wheels for Python 3.13 on https://pypi.org/project/lz4/.

**Comment by jonathanunderwood** [comment]
Yes; this is in progress. I am taking the opportunity to shift across to
leveraging UV and meson-python for building in order to solve a number of
issues. 3.13 wheels will come with that work.

**Pull request merged**
