### PR TITLE
Optionally disable contentSize frame header

### LINKED ISSUE #21: Feature Request: enable simple frame compression without content-size header
The lz4 frame specification makes the content-size header field optional. I would love to be able to `lz4.frame.compress(foo, content_size=False)` and have the encoded frame not include the C.Size FLG and the optional 8 bytes of size data.

For example, the lz4f package does not include the content-size header and results in different bits:

```
In [1]: import lz4f
In [2]: lz4f.compressFrame(b'1234')
Out[2]: '\x04"M\x18`@\x82\x04\x00\x00\x801234\x00\x00\x00\x00'
In [3]: import lz4.frame
In [4]: lz4.frame.compress(b'1234')
Out[4]: '\x04"M\x18h@\x04\x00\x00\x00\x00\x00\x00\x00\xcd\x04\x00\x00\x801234\x00\x00\x00\x00'
```

### PR DESCRIPTION
**Pull request by dpkp**
Fixes #21 w/ test

### CODE REVIEW

**Comment by jonathanunderwood** [comment]
I am on a train, so can't look at the detail, but I like the intent. I wonder if we should actually be setting this in compress_begin though. As I say, hard to remind myself of the code, so may be totally off base :) will take a closer look at the weekend. Also it looks like the appveyor build is failing.

Thanks for working in this!

**Comment by dpkp** [comment]
I added a new flag (content_size=True|False) to both compress and compress_begin. It looks to me like those are the main functions used to create a frame header, and where the current code sets the contentSize value. The PR includes a test that fails and a patch that causes it to pass.

**Comment by jonathanunderwood** [comment]
I merged this, but now looking at it again I think I am going to revert it, as it duplicates existing functionality.

Prior to this change, if you don't want the content size header you simply specify source_size=0 (which was the default anyway). So, I really don't think this is useful. Have I missed something?

**Comment by jonathanunderwood** [comment]
Oh, OK, I actually see what you were trying to do - you were trying to make it possible to disable the content header for the `compress` function - it was already possible to do it for the `compress_begin+compress_update+compress_flush` way of working.

**Pull request merged**
